name: BorrowSanitizer
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  bsan:
    name: Run BorrowSanitizer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/borrowsanitizer/bsan:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests with BorrowSanitizer
        run: |
          cargo bsan test
