name: Release

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Operation"
        required: true
        type: choice
        default: dryrun
        options:
          - dryrun
          - publish

concurrency:
  group: release
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: "true"
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
    needs:
      - release-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Publish Crate
        run: |
          set -euxo pipefail
          export DRYRUN=--dry-run
          if [ "${{ inputs.operation }}" = "publish" ]];then
              export DRYRUN=""
          fi
          cargo package --list
          cargo publish $DRYRUN
          export TAG_NAME=v${{ needs.check-version.outputs.version }}
          [ $(expr "x$TAG_NAME" : "x[0-9\.]*$") -eq 0 ] && exit 1
          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push $DRYRUN origin $TAG_NAME

  release-checks:
    name: Release Checks
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - check-version
      - run-ci
      - run-heavy
    steps:
      - name: Job outcomes
        run: |
          echo "Version job status: ${{ needs.check-version.result }}"
          echo "CI job status: ${{ needs.ci.result }}"
          echo "Heavy job status: ${{ needs.heavy.result }}"
      - if: ${{ needs.check-version.result != 'success' }}
        run: exit 1
      - if: ${{ inputs.operation == 'publish' && needs.ci.result != 'success' }}
        run: exit 1
      - if: ${{ ${{ inputs.operation == 'publish' && needs.semver-checks.result != 'success' }}
        run: exit 1

  run-ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    if: inputs.operation == 'publish' && github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
    needs:
      - check-version

  run-heavy:
    name: Heavy Tests
    uses: ./.github/workflows/heavy.yml
    if: inputs.operation == 'publish' && github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
    needs:
      - check-version

  check-version:
    name: Version Checks
    runs-on: ubuntu-latest
    if: github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
    outputs:
      version: "${{ steps.version.outputs.version }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check version
        id: version
        run: |
          set -euxo pipefail
          ./.github/workflows/check_version.py
