name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string
      operation:
        description: "Operation"
        required: true
        type: choice
        default: dryrun
        options:
          - dryrun
          - publish

concurrency:
  group: release
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: "true"
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  release:
    name: All Release Stages
    runs-on: ubuntu-latest
    if: github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
    needs:
      - ci-main
      - heavy-main
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Publish Crate
        run: cargo publish --dry-run

  ci-main:
    name: CI
    uses: ./.github/workflows/ci.yml
    if: github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'

  heavy-main:
    name: Heavy Tests
    uses: ./.github/workflows/heavy.yml
    if: github.repository_owner == 'meduketto' && github.ref == 'refs/heads/main'
